# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
