# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configproperty',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
