# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=64)),
                ('dataset_title', models.CharField(max_length=256)),
                ('subject_title', models.CharField(default='Downloads', max_length=64)),
                ('value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(max_length=4)),
                ('since', models.CharField(max_length=20)),
            ],
        ),
    ]
