# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationStatistic',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('organisation_name', models.CharField(max_length=64)),
                ('dataset_title', models.CharField(max_length=256)),
                ('value', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(max_length=4)),
                ('since', models.CharField(max_length=20)),
            ],
        ),
    ]
