# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationstatistic',
            name='subject_title',
            field=models.CharField(default='Downloads', max_length=64),
        ),
    ]
