# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_organisationstatistic_subject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationstatistic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
