# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_datafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='countries',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='countries_other',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='frequency',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='notifications',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='themes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='licence',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='licence_other',
            field=models.TextField(default=''),
        ),
    ]
