# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0004_auto_20161128_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='countries',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='countries_other',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='frequency',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='licence_other',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='notifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='themes',
            field=models.TextField(default='[]'),
        ),
    ]
