# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0006_dataset_last_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
