# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0012_auto_20161219_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='frequency_weekly_end',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='frequency_weekly_start',
        ),
        migrations.AddField(
            model_name='datafile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='quarter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datafile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
