# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0012_dataset_summary'),
        ('drafts', '0013_auto_20161220_1212'),
    ]

    operations = [
    ]
