# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishinguser',
            name='apikey',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
