# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
