# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_related_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
    ]
