# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170206_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
