# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170206_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhiddentask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userhiddentask',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserHiddenTask',
        ),
    ]
