# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('abbreviation', models.CharField(default='', max_length=32, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('closed', models.BooleanField(default=False)),
                ('replaced_by', models.CharField(default='', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_name', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('foi_email', models.CharField(default='', max_length=200)),
                ('foi_name', models.CharField(default='', max_length=200)),
                ('foi_phone', models.CharField(default='', max_length=200)),
                ('foi_web', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
